### ISSUE TITLE
sage-shell-edit:send-region doesn't work if file does not end in `.sage`

### ISSUE THREAD

**Issue by jsrndk** [stakemori/sage-shell-mode#10]
If the edited file does not end in `.sage`, then `sage-shell-edit:send-region` will create a file with `.sobj` extension, but the called `load` function will look for a `<extension>.sobj` file.

**Comment by stakemori** [comment]
Thanks for reporting, Johan. I just fixed this in 541d48d58c793993e7dcdf42efa836061be949ae. I will merge it to master later.

**Comment by jsrndk** [comment]
Wow, so fast - thanks!

**Comment by jsrndk** [comment]
I confirm that this works for me now. Thanks again.
