### ISSUE TITLE
cannot move around in the buffer while sage is printing stuff

### ISSUE THREAD

**Issue by mantepse** [stakemori/sage-shell-mode#19]
Consider the following silly program:
```
i = 2
while i<100:
    i = next_prime(i)
    print i
```
I have frequently programs which output a lot, and take a long time to do that - but I want them to finish.

However, while the program is working, I like to go around in the buffer and read stuff.  Unfortunately, this is currently not possible in `sage-shell-mode`.

**Comment by stakemori** [comment]
I just fixed this in 09b067b63c75d9ea97bfaf847d5e41b6b41f38d9. It is not merged to master yet. I will test it for a while. If it is OK, then I will merge it to mater later. Thanks for reporting.

**Comment by stakemori** [comment]
I just merged the fix to master. Thanks for reporting.
