### ISSUE TITLE
auto complete on from sage.<TAB>

### ISSUE THREAD

**Issue by malb** [stakemori/sage-shell-mode#2]
I often find myself typing "from sage.rings.all import P…" or so and it would be awesome if sage-shell-mode could offer me some auto-completion options for that.

(One option to realise this feature could be to use jedi-mode, but it's not like I understand the emacs+python eco-system well enough to judge)

**Comment by stakemori** [comment]
I think it is not so hard to implement such a feature. I probably implement it when I have enough time.

**Comment by stakemori** [comment]
In recent commits, I implemented this feature. Please update `sage-shell-mode` and `auto-complete-sage` to the latest version.

I added a new customizable variable `ac-sage-complete-on-dot`. This is similar to `jedi:complete-on-dot` in `jedi-core.el`. When it is `non-nil`, `auto-complete` starts when a dot is inserted.

If you are using the ac-source provided by `jedi`, please call `jedi:setup` before calling `ac-sage-setup`. Then the ac-source provided by `jedi` is preferred.
