### ISSUE TITLE
sage-shell-edit:send-line* C-c C-j

### ISSUE THREAD

**Issue by mantepse** [stakemori/sage-shell-mode#22]
`sage-shell-edit:send-line*` currently sends the current line to the sage buffer.

In `sage-mode` the key `C-c C-j` did something related, but (in my opinion) more useful: if the current line does not begin with "sage: ", it does nothing.

Otherwise, it sends the block (possibly continued with `....:`) to the sage buffer, and puts point to the next `sage: ` prompt in the current buffer.

This is extremely useful to evaluate code from docstrings, but I also use it in email...

**Comment by stakemori** [comment]
I just added such a command (`sage-shell:send-doctest`) in c0358730321c469503d60b8f04a71ba7d5ff1f96. It is not in master yet. I will test it for a while. Thanks for your suggestion.

**Comment by stakemori** [comment]
`sage-shell:send-doctest` is now available in master.
