### ISSUE TITLE
auto-complete for attached files

### ISSUE THREAD

**Issue by malb** [stakemori/sage-shell-mode#3]
I tend to attach("filename.py") the files I'm currently working on. It would be nice if the functions/classes found in filename.py could be added to the auto complete database.

**Comment by stakemori** [comment]
Thanks for the report. I use only `load` or `import` for loading a file. So I do not notice this.

I just updated this repository. In a few hours, Melpa will re-build this package. Please wait for a few hours, and update `sage-shell-mode` by `list-packages RET U RET x`.

By the way, you can `attach` a file by `M-x sage-shell-edit:attach-file`.

I hope this update helps you.

**Comment by malb** [comment]
Thank you, it works as expected. :+1:
