### ISSUE TITLE
Bug in sage-shell:delchar-or-maybe-eof

### ISSUE THREAD

**Issue by dszgit** [stakemori/sage-shell-mode#4]
The function (sage-shell:delchar-or-maybe-eof) is supposed to check whether (point) is at end of buffer, but it doesn't.  As a result, if you enter text at the prompt, then move to beginning of input (Ctrl-A), then typing Ctrl-D does the wrong (and very confusing) thing.

Otherwise very nice package!

Here is a patch:

```
--- a/sage-shell-mode.el
+++ b/sage-shell-mode.el
@@ -655,7 +655,7 @@ returned from the function, otherwise, this returns it self. "
 Sends an EOF only if point is at the end of the buffer and there is no input. "
   (interactive "p")
   (let ((proc (get-buffer-process (current-buffer))))
-    (if (and proc (= (point) (marker-position (process-mark proc)))
+    (if (and proc (= (point) (point-max) (marker-position (process-mark proc)))
              (sage-shell:output-finished-p)
              (sage-shell:redirect-finished-p))
         (sage-shell:send-eof)
```

**Comment by stakemori** [comment]
Thank you very much for reporting the bug and sending the patch. I have fixed it in c04ab9b.
